server:
  port: 8090
spring:
  application:
    name: spring-cloud-alibaba-sentinel
  cloud:
    gateway:
      routes:
        - id: hello1
          uri: http://127.0.0.1:8763
          predicates:
            - Path=/hello1/**
          filters:
            - RewritePath=/hello1/?(?<segment>.*), /hello/$\{segment}
        - id: hello2
          uri: http://127.0.0.1:8764
          predicates:
            - Path=/hello2/**
          filters:
            - RewritePath=/hello2/?(?<segment>.*), /hello/$\{segment}